version: 2
jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources
  build:
    docker:
      # We do not need node for building this image. But we need other things this provides.
      - image: circleci/node:10
        user: root
    environment:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - run: tools/gcloud_install.sh
      - run:
          name: GCP Authenticate
          command: |
            echo 'export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"' >> $BASH_ENV
            tools/gcp_authenticate.sh
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker login
          command: |
            echo 'export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"' >> $BASH_ENV
            tools/docker_login.sh
      - run:
          name: Docker build and push
          command: |
            echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
            echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
            tools/docker_build_push.sh
  trigger-dependants:
    docker:
      - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    steps:
      - run:
          name: Trigger dependant builds
          command: |
            echo 'export CIRCLE_API_TOKEN="$CIRCLE_API_TOKEN"' >> $BASH_ENV
            tools/downstream_single_trigger.sh "github/entur/tiamat/" "master"
            tools/downstream_single_trigger.sh "github/entur/ishtar/" "master"
workflows:
  version: 2
  build-toolbox-image:
    jobs:
      - shellcheck
      - build:
          context: org-carbon
          requires:
            - shellcheck
      - trigger-dependants:
          context: org-carbon
          requires:
            - build