version: 2
aliases:
  - &post_build
    name: Trigger downstream builds
    command: |
      echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
      echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
      echo 'export GITHUB_TOKEN="$GITHUB_TOKEN"' >> $BASH_ENV

      /tools/trigger_build.sh "entur/entur/abzu.git" "master" "$(git log -1 --pretty=%B)"
      /tools/trigger_build.sh "entur/entur/bel.git" "master" "$(git log -1 --pretty=%B)"
      /tools/trigger_build.sh "entur/entur/chouette2.git" "rutebanken_develop" "$(git log -1 --pretty=%B)"
      # Netex should be built before netex-java-model
      /tools/trigger_build.sh "entur/entur/netex.git" "master" "$(git log -1 --pretty=%B)"
      /tools/trigger_build.sh "entur/entur/otp-travelsearch-qa.git" "master" "$(git log -1 --pretty=%B)"
      /tools/trigger_build.sh "entur/entur/r5.git" "master" "$(git log -1 --pretty=%B)"
      /tools/trigger_build.sh "entur/entur/deploybot.git" "master" "$(git log -1 --pretty=%B)"

jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources
  build:
    docker:
      # We do not need node for building this image. But we need other things this provides.
      - image: circleci/node:10
        user: root
    environment:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - run: tools/gcloud_install.sh
      - run:
          name: GCP Authenticate
          command: |
            echo 'export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"' >> $BASH_ENV
            tools/gcp_authenticate.sh
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker login
          command: |
            echo 'export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"' >> $BASH_ENV
            tools/docker_login.sh
      - run:
          name: Docker build and push
          command: |
            echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
            echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
            tools/docker_build_push.sh
  trigger-dependants:
    docker:
    - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
      auth:
        username: _json_key
        password: $GCLOUD_SERVICE_KEY
    steps:
    - checkout
    - run: *post_build
workflows:
  version: 2
  build-toolbox-image:
    jobs:
      - shellcheck
      - build:
          context: org-carbon
          requires:
            - shellcheck
      - trigger-dependants:
          context: org-carbon
          requires:
          - build