version: 2
jobs:
  build:
    docker:
      - image: circleci/build-image
    environment:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - run:
        name: GCP Authenticate
        command: tools/gcp_authenticate.sh
        environment:
          GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY
      - setup_remote_docker:
          docker_layer_caching: true
      - run: tools/docker_login.sh
      - run: tools/docker_build_push.sh
