version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
        user: root
    environment:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - run: tools/gcloud_install.sh
      - run:
          name: GCP Authenticate
          command: |
            echo 'export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"' >> $BASH_ENV
            tools/gcp_authenticate.sh
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker login
          command: |
            echo 'export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"' >> $BASH_ENV
            tools/docker_login.sh
      - run:
          name: Docker build and push
          command: |
            echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
            echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
            tools/docker_build_push.sh
workflows:
  version: 2
  build-toolbox-image:
    jobs:
      - build:
          context: org-carbon