version: 2
jobs:
  build:
    docker:
      - image: circleci/build-image
    environment:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - run: tools/gcloud_install.sh
      - run:
          name: GCP Authenticate
          command: tools/gcp_authenticate.sh
          environment:
            GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: GCP Authenticate
          command: tools/docker_login.sh
          environment:
            GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY
      - run: tools/docker_build_push.sh
